/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Pet } from "./Pet";
import { PetCountArgs } from "./PetCountArgs";
import { PetFindManyArgs } from "./PetFindManyArgs";
import { PetFindUniqueArgs } from "./PetFindUniqueArgs";
import { CreatePetArgs } from "./CreatePetArgs";
import { UpdatePetArgs } from "./UpdatePetArgs";
import { DeletePetArgs } from "./DeletePetArgs";
import { Order } from "../../order/base/Order";
import { PetCategory } from "../../petCategory/base/PetCategory";
import { Review } from "../../review/base/Review";
import { PetService } from "../pet.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Pet)
export class PetResolverBase {
  constructor(
    protected readonly service: PetService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pet",
    action: "read",
    possession: "any",
  })
  async _petsMeta(
    @graphql.Args() args: PetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Pet])
  @nestAccessControl.UseRoles({
    resource: "Pet",
    action: "read",
    possession: "any",
  })
  async pets(@graphql.Args() args: PetFindManyArgs): Promise<Pet[]> {
    return this.service.pets(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Pet, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pet",
    action: "read",
    possession: "own",
  })
  async pet(@graphql.Args() args: PetFindUniqueArgs): Promise<Pet | null> {
    const result = await this.service.pet(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pet)
  @nestAccessControl.UseRoles({
    resource: "Pet",
    action: "create",
    possession: "any",
  })
  async createPet(@graphql.Args() args: CreatePetArgs): Promise<Pet> {
    return await this.service.createPet({
      ...args,
      data: {
        ...args.data,

        order: args.data.order
          ? {
              connect: args.data.order,
            }
          : undefined,

        petCategory: args.data.petCategory
          ? {
              connect: args.data.petCategory,
            }
          : undefined,

        review: args.data.review
          ? {
              connect: args.data.review,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Pet)
  @nestAccessControl.UseRoles({
    resource: "Pet",
    action: "update",
    possession: "any",
  })
  async updatePet(@graphql.Args() args: UpdatePetArgs): Promise<Pet | null> {
    try {
      return await this.service.updatePet({
        ...args,
        data: {
          ...args.data,

          order: args.data.order
            ? {
                connect: args.data.order,
              }
            : undefined,

          petCategory: args.data.petCategory
            ? {
                connect: args.data.petCategory,
              }
            : undefined,

          review: args.data.review
            ? {
                connect: args.data.review,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pet)
  @nestAccessControl.UseRoles({
    resource: "Pet",
    action: "delete",
    possession: "any",
  })
  async deletePet(@graphql.Args() args: DeletePetArgs): Promise<Pet | null> {
    try {
      return await this.service.deletePet(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Order, {
    nullable: true,
    name: "order",
  })
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "any",
  })
  async getOrder(@graphql.Parent() parent: Pet): Promise<Order | null> {
    const result = await this.service.getOrder(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => PetCategory, {
    nullable: true,
    name: "petCategory",
  })
  @nestAccessControl.UseRoles({
    resource: "PetCategory",
    action: "read",
    possession: "any",
  })
  async getPetCategory(
    @graphql.Parent() parent: Pet
  ): Promise<PetCategory | null> {
    const result = await this.service.getPetCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Review, {
    nullable: true,
    name: "review",
  })
  @nestAccessControl.UseRoles({
    resource: "Review",
    action: "read",
    possession: "any",
  })
  async getReview(@graphql.Parent() parent: Pet): Promise<Review | null> {
    const result = await this.service.getReview(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
